### ISSUE TITLE
error for Ios device 

### ISSUE THREAD

**Issue by Niccolohui** [thyagoluciano/flutter_launch_whatsapp#2]
Hi, I got this error when I use the plugin

Error output from Xcode build:
↳
    2018-08-31 02:10:27.696 xcodebuild[17787:13510807] [MT] PluginLoading: Required plug-in compatibility UUID B395D63E-9166-4CD6-9287-6889D507AD6A for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Unity4XC.xcplugin' not present in DVTPlugInCompatibilityUUIDs
    2018-08-31 02:10:28.916 xcodebuild[17787:13510858]  DTDeviceKit: deviceType from 7ef5759c35144087cd7298836bd67d074080238a was NULL
    2018-08-31 02:10:28.917 xcodebuild[17787:13510871]  DTDeviceKit: deviceType from e645298f005a69e72fc3b76d02738b47fe6df710 was NULL
    ** BUILD FAILED **
    
Xcode's output:
↳
    The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.
    The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.
Could not build the precompiled application for the device.

this is my flutter doctor

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.5.1, on Mac OS X 10.13.1 17B1003, locale en-HK)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
[✓] iOS toolchain - develop for iOS devices (Xcode 9.2)
[✓] Android Studio (version 3.1)
[✓] Connected devices (3 available)

thank you!!!!!

**Comment by thyagoluciano** [comment]
You added this setting?

Add the following entry to your Info.plist file, located in /ios/Runner/Info.plist:
````xml
<key>LSApplicationQueriesSchemes</key>
<array>
  <string>whatsapp</string>
</array>
````

**Comment by Niccolohui** [comment]
yes, i did

**Comment by aamansilla** [comment]
i have the same problem. Please, can you comment any solution??

**Comment by thyagoluciano** [comment]
Today I updated this version to fix this problem.

**Comment by siliosffreitas** [comment]
> Today I updated this version to fix this problem.

I am using version ^0.2.0 and I have the same problem:

$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.6.5, on Mac OS X 10.14.4 18E227, locale en-BR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.4)
[✓] Connected device (1 available)

• No issues found!

**Comment by siliosffreitas** [comment]
after doing a downgrade of the cocoapods version worked.
