### ISSUE TITLE
Please solve Android V2 for Flutter 2.5

### ISSUE THREAD

**Issue by carmas123** [thyagoluciano/flutter_launch_whatsapp#26]
Please can you migrate you lib to V2 embedding?

https://flutter.dev/go/android-plugin-migration.

Regards

**Comment by KANekT** [comment]
https://github.com/KANekT/flutter_launch_whatsapp

I wanted to update, but I don't understand how to fix Android

**Comment by thyagoluciano** [comment]
Thanks for using this plugin, I just generated a new version 0.3.0
