### ISSUE TITLE
build failed with an exception

### ISSUE THREAD

**Issue by osamagamal65** [thyagoluciano/flutter_launch_whatsapp#4]
build failed with this excecption 
`C:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_launch-0.1.2\android\src\main\kotlin\com\example\flutterlaunch\FlutterLaunchPlugin.kt: (33, 42): Type inference failed. Expected type mismatch: inferred typeis String? but String was expected`
flutter doctor results are 
` Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.10.2, on Microsoft Windows [Version 10.0.17134.345], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.2)
[√] Android Studio (version 3.1)
[√] VS Code (version 1.27.2)
[√] VS Code, 64-bit edition (version 1.28.2)
[√] Connected device (1 available)

• No issues found! `

**Comment by thyagoluciano** [comment]
Today I updated this version to fix this problem.
