### ISSUE TITLE
whatsapp not launching

### ISSUE THREAD

**Issue by ayazkhalid** [thyagoluciano/flutter_launch_whatsapp#5]
MissingPluginException(No implementation found for method launchWathsApp on channel flutter_launch)

**Comment by SamillyNunes** [comment]
I had the same error. Can someone help us?

**Comment by ayazkhalid** [comment]
Mine woked by using old version

**Comment by SamillyNunes** [comment]
Really? What version?

**Comment by ayazkhalid** [comment]
let me see w8 a sec

**Comment by SamillyNunes** [comment]
Alright, thanks

**Comment by ayazkhalid** [comment]
oh i used url_launcher plugin when it didnt work

**Comment by SamillyNunes** [comment]
But url_launcher it is for calls and messages.And the Whatsapp?

**Comment by ayazkhalid** [comment]
url_launcher: 4.0.0 in pubspec.yml

import 'package:url_launcher/url_launcher.dart';

    var whatsappUrl ="whatsapp://send?phone=${_numberController.text}&text=${_textController.text}";
        await canLaunch(whatsappUrl)? launch(whatsappUrl):print("open whatsapp app link or do a snackbar with notification that there is no whatsapp installed");

**Comment by ayazkhalid** [comment]
works fine for me

**Comment by SamillyNunes** [comment]
Wow, you're genius!!! Thank u so much!

**Comment by ayazkhalid** [comment]
:)

**Comment by thyagoluciano** [comment]
Today I updated this version to fix this problem.

**Comment by AqsaShaikh1** [comment]
> 
> 
> works fine for me

hey , can you paste your main.dart file for reference.

**Comment by AqsaShaikh1** [comment]
> 
> 
> Today I updated this version to fix this problem.
hi,
It's still giving me the same error.

What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.10 and higher.
The following dependencies do not satisfy the required version:
root project 'android' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71

can you please help
