### ISSUE TITLE
Kotlin Gradle plugin

### ISSUE THREAD

**Issue by stephane-couget** [thyagoluciano/flutter_launch_whatsapp#6]
Hello,

I'm obtaining this error this day with flutter_launch.

info flutter.tools * What went wrong:
info flutter.tools The Android Gradle plugin supports only Kotlin Gradle plugin version 1.2.51 and higher. Project 'flutter_launch' is using version 1.1.51.

Could you recompile your plugin with at least 1.1.51 and more from kotlin gradle plugin ?
In the meantime, I disable the plugin to continue my development.

Congratulations on all the work done so far.

**Comment by apropsi** [comment]
+1

**Comment by jesaiasmaia** [comment]
+1

**Comment by thyagoluciano** [comment]
Today I updated this version to fix this problem.
